### ISSUE TITLE
Segmentation fault - objects created by a coroutine.

### ISSUE THREAD

**Issue by merlinblack** [luabind/luabind#1]
I've found that objects (class instances) created by a Lua coroutine will cause a segfault when garbage collected by the main thread, unless the coroutine releases the objects and forces a garbage collection before it ends.  This I guess is happening as the coroutine thread no longer exists, and the object has some connection to it, which is needed at destruction.  I'm not sure how hard this would be to change to always create objects against the main thread.

Here is a small program which shows the problem.

```
#include <iostream>
#include <lua.hpp>
#include <luabind/luabind.hpp>

using namespace luabind;

class test
{
public:
    test()
    {
        std::cout << "test constructor" << std::endl;
    }
    ~test()
    {
        std::cout << "test destructor" << std::endl;
    }
};

int main()
{
    lua_State *L;

    L = lua_open();

    luaL_openlibs( L );

    luabind::open(L);

    module(L)
    [
        class_<test>("myclass")
        .def(constructor<>())
    ];

    if( luaL_dostring( L, 
                "function func()\n"
                "    instance = myclass()\n"
                "    print'Instance created'\n"
                "end\n"
                "function test()\n"
                "    co = coroutine.wrap(func)\n"
                "    co()\n"
                "    instance = nil\n"
                "    print 'Instance no longer referenced'\n"
                "end\n"
                "for i=1,100 do test() end\n"
                ))
    {
        object error( from_stack( L, 1 ) );
        std::cout << error << std::endl;
    }

    lua_close( L );
}
```

**Comment by neomantra** [comment]
Hi,
I just tested this and it works in luabind 0.9.
-Evan

**Comment by merlinblack** [comment]
Hi Evan,
Indeed, when I first tried 0.9, it looked like the bug had been squashed.  However after a reboot (i.e. random values in memory different) it showed up again.  The bug seems fairy transient.  I guess that when a coroutine thread is garbage collected, the memory some times is not reused, by the time the class instance is destructed, and the segfault does not occur.  Like wise if by chance the class instance is garbage collected before the thread.  Note in my example code, the 'test' is done 100 times.  This was because the bug rarely showed up on the first or second times.  Perhaps changing this to 1000 times or so, may reveal the bug in your environment.

Thanks
- Nigel

**Comment by neomantra** [comment]
Nigel,
We are working through some other memory corruption bug, which may be related to what you are seeing.  I will update you on our findings and thn try this case with a higher count. 
-Evan

**Comment by merlinblack** [comment]
I've just tried it again, with a fresh download of ver 0.9.0 on another machine, and it seems to be now working.  It survived 10000 iterations, with out seg faulting, so I fairly sure it's behaving.  I'll know for sure when I retry it in the program I was originally having problems with.  I'm wondering if it was picking up the older 8.1 lib perhaps. g++ can be hairy like that.

Thanks
-Nigel
